#!/usr/bin/perl
use strict;
use warnings;

sub backup($);

my $dir = "$ENV{HOME}/Code/n900";

my %gitRepos = (
);

sub main(@){
  die "Usage: $0\n" if @_ != 0;

  print "making sure n900 is ssh-able\n";
  system "n900", "-s", "echo found n900!\n";
  die "failed" if $? != 0;

  my %preHeads = map {$_ => getGitHead($gitRepos{$_})} keys %gitRepos;

  backup "rtcom-backup";
  backup "dcim-backup";

  my %postHeads = map {$_ => getGitHead($gitRepos{$_})} keys %gitRepos;
  for my $repo(sort keys %gitRepos){
    if($preHeads{$repo} ne $postHeads{$repo}){
      print "\nrepo $repo updated:\n";
      system "cd $gitRepos{$repo}; git --no-pager show HEAD";
    }
  }
}

sub getGitHead($){
  my $dir = shift;
  my $h = `cd $dir; git rev-parse HEAD`;
  chomp $h;
  return $h;
}

sub backup($){
  my $backupScript = shift;

  print "\n\n\n=========$backupScript\n";
  system "$dir/$backupScript";

  die "$backupScript failed" if $? != 0;
}

&main(@ARGV);
