#!/usr/bin/perl
use strict;
use warnings;

my $DEV = '/dev/ttyACM0';
my $CONFIG = `echo -n \$HOME/Desktop/N900/config/utils/wvdial.conf`;
my $resolvChooserExec = `echo -n \$HOME/bin/resolvchooser`;

my $arg = shift;
$arg = 'toggle' if not defined $arg;
if(($arg ne 'on' and $arg ne 'off' and $arg ne 'toggle') or @ARGV > 0){
  die "Usage: $0 [on|off|toggle]  {toggle is default}\n";
}


if($arg ne 'off' and not -e $DEV){
  print STDERR "Device $DEV not found:\nrunning $0 off instead of $0 $arg\n";
  $arg = 'off';
}

if($arg eq 'toggle'){
  system "pidof pppd wvdial";
  my $isUp = $? == 0;
  $arg = $isUp ? 'off' : 'on';
}

my $peerFile = '/etc/ppp/peers/wvdial';

if($arg eq 'on'){
  print "Turning tethering ON and NetworkManager OFF\n";
  my @lines = `cat $peerFile`;
  for my $line(@lines){
    $line =~ s/^usepeerdns\n?$//;
  }
  open FH, "> $peerFile" or die "Could not write to $peerFile\n$!";
  print FH @lines;
  close FH;
  system 'killall', '-9', 'pppd', 'wvdial';
  system "initctl stop network-manager";
  system "$resolvChooserExec default";
  system 'wvdial', '-C', $CONFIG;
}elsif($arg eq 'off'){
  print "Turning tethering OFF and NetworkManager ON\n";
  system "initctl start network-manager";
  system 'killall', '-9', 'pppd', 'wvdial';
}
