#!/usr/bin/perl
use strict;
use warnings;

my $file = '/home/user/.count';

my $arg = shift || '';
if(@ARGV != 0 or ($arg ne '' and $arg ne 'reset')){
  die "Usage:
   $0
   $0 reset";
}

my $num = `cat $file 2>/dev/null`;
$num++;
print "$num\n";


if($arg eq 'reset'){
  $num = 0;
}

system "echo $num > $file";

