#!/usr/bin/perl
use Time::HiRes qw(sleep);

system "qcmd next 1>/dev/null 2>/dev/null &";
sleep 0.5;
system "killall mplayer 1>/dev/null 2>/dev/null &";
system "qcmd start 1>/dev/null 2>/dev/null &";

