#!/usr/bin/perl
use strict;
use warnings;

my $btn = shift;
$btn = '' if not defined $btn;

my $pid = `pidof rhythmbox`;
$pid = $pid=~/^[0-9]+\n?$/;


if($btn eq 'play-pause'){
  print "►|| \n";
  if($pid){
    system "sudo debian " .
           "/home/user/bin/rc --play-pause " .
           "> /dev/null 2>&1";
  }
}elsif($btn eq 'pause'){
  print "||   \n";
  if($pid){
    system "sudo debian " . 
           "/home/user/bin/rc --pause " .
           "> /dev/null 2>&1";
  }
}elsif($btn eq 'next'){
  #print "»\n";
  print '\\\\ \\\\ 
// // 
';
  if($pid){
    system "sudo debian " .
           "/home/user/bin/rc --next " .
           "> /dev/null 2>&1";
  }
}elsif($btn eq 'previous'){
  #print "«\n";
  print '// // 
\\\\ \\\\ 
';
  if($pid){
    system "sudo debian " .
           "/home/user/bin/rc --previous " .
           "> /dev/null 2>&1";
  }
}elsif($btn eq 'next-huge'){
  my $skip = '
\@@@@\    \@@@@\
 \@@@@\    \@@@@\
  \@@@@\    \@@@@\
   \@@@@\    \@@@@\
    \@@@@\    \@@@@\
    /@@@@/    /@@@@/
   /@@@@/    /@@@@/
  /@@@@/    /@@@@/
 /@@@@/    /@@@@/
/@@@@/    /@@@@/
';
  $skip =~ s/^\n//;
  print $skip;
  if($pid){
    system "sudo debian " .
           "/home/user/bin/rc --next " .
           "> /dev/null 2>&1";
  }
}elsif($btn eq 'print-playing'){
  if($pid){
    system "sudo debian " .
           "/home/user/bin/rc --print-playing " .
           "2> /dev/null";
  }else{
    print "Rhythmbox not running" . ' 'x17 . "\n";
  }
}else{
die "
Usage: $0 BUTTON
BUTTON is one of [play-pause|pause|next|
                  previous|next-huge|print-playing]
";
}
